### ISSUE TITLE
Game does not read player left amount correctly.

### ISSUE THREAD

**Issue by ZekeZDev** [NucleoidMC/Sabotage#15]
Testing this on my server I found that when we had 9 players it worked until the 7th players death and the logs just stated that 
"X has died 7 players left"
"X has died 7 players left"
"X has died 7 players left"
"X has died 7 players left"
this was continuously spammed and not related to people actually dying

**Comment by ellieisjelly** [comment]
Do you have any way of reproducing this? Any specific quirks that could've possibly caused it?
