### ISSUE TITLE
Chests disappear when opened without an animation

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/Sabotage#4]
Currently, opening a chest only plays a sound; the chest itself disappears immediately. Could an animation be implemented as visual feedback, such as the chest lid opening followed by the chest disappearing in a puff of smoke?

**Comment by ellieisjelly** [comment]
the puff of smoke sounds like a good idea, though the lid opening would slow down the collection process as players could try to open chests that were already open. i'll probaby look into this
